language: generic
sudo: required
dist: trusty

services:
  - docker

script:
  - docker build --target nginx --rm -t nginx:1.16.0 .
  - docker images

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME/nginx:1.16.0"
  - docker logout

disabled_script:
  - docker build --target openssl --rm -t openssl:1.1.1b .
  - docker build --target sqlite --rm -t sqlite:3.28.0 .
  - docker build --target python --rm -t python:3.7.3 .
  - docker tag `docker images --filter "label=image=nginx:1.16.0" --format "{{.CreatedAt}}\t{{.ID}}" | sort -nr | head -n 1 -q | cut -f2` donizyo/nginx:1.16.0
  - docker push donizyo/nginx:1.16.0
  - docker push donizyo/python:3.7.3
