language: generic
sudo: required
dist: trusty

services:
  - docker

script:
  - docker build --target sqlite --rm -t sqlite:3.28.0 .
  - docker tag $(docker images --filter "label=image=nginx:1.16.0" --format "{{.CreatedAt}}\t{{.ID}}" | sort -nr | head -n 1 -q | cut -f2) donizyo/nginx:1.16.0
  - docker images
