language: generic
sudo: required
dist: trusty

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull $DOCKER_USERNAME/python:3.7.3 && docker tag $DOCKER_USERNAME/python:3.7.3 python

script:
  - docker build -t bind ./bind
  - docker images

after_success:
  - docker tag bind $DOCKER_USERNAME/bind:9.14.2 && docker push $DOCKER_USERNAME/bind:9.14.2

after_script:
  - docker logout
