language: generic
sudo: required
dist: trusty

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t base ./base
  - docker build -t openssl:1.1.0k ./openssl
  - docker build -t sqlite:3.28.0 ./python/sqlite
  - docker build -t python:3.7.3 ./python
  - docker images

after_success:
  - docker tag openssl:1.1.0k $DOCKER_USERNAME/openssl:1.1.0k && docker push $DOCKER_USERNAME/openssl:1.1.0k
  - docker tag sqlite:3.28.0 $DOCKER_USERNAME/sqlite:3.28.0 && docker push $DOCKER_USERNAME/sqlite:3.28.0
  - docker tag python:3.7.3 $DOCKER_USERNAME/python:3.7.3 && docker push $DOCKER_USERNAME/python:3.7.3

after_script:
  - docker logout

disabled_script:
  - #docker pull $DOCKER_USERNAME/sqlite:3.28.0 && docker tag $DOCKER_USERNAME/sqlite:3.28.0 sqlite
