language: generic
sudo: required
dist: trusty

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull $DOCKER_USERNAME/sqlite:3.28.0
  - docker tag $DOCKER_USERNAME/sqlite:3.28.0 sqlite

script:
  - docker build -t python:3.7.3 ./python
  - docker images

after_success:
  - docker tag python:3.7.3 $DOCKER_USERNAME/python:3.7.3
  - docker push $DOCKER_USERNAME/python:3.7.3

after_script:
  - docker logout
