language: generic
sudo: required
dist: trusty

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull $DOCKER_USERNAME/openssl:1.1.0k
  - docker tag $DOCKER_USERNAME/openssl:1.1.0k openssl

script:
  - docker build -t sqlite:3.28.0 ./python/sqlite
  - docker images

after_success:
  - docker tag sqlite:3.28.0 $DOCKER_USERNAME/sqlite:3.28.0
  - docker push $DOCKER_USERNAME/sqlite:3.28.0

after_script:
  - docker logout

disabled_script:
  - docker build -t python:3.7.3 ./python
  - docker tag python:3.7.3 $DOCKER_USERNAME/python:3.7.3
  - docker push $DOCKER_USERNAME/python:3.7.3
